# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

os:
  - linux
  - osx

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - os: osx
      python: 3.4
      language: generic
      env: TOXENV=py34
    - os: osx
      python: 3.5
      language: generic
      env: TOXENV=py35
    - os: osx
      python: 3.6
      language: generic
      env: TOXENV=py36
  allow_failures:
    - os: osx

env:
  global:
    # $PYPIPASSWORD
    secure: qo57dxY6zF76pgz34Qq5a4W0o/ra9hMCAg6xivX7XOehE6vyN/tQkm5V9ZknvXEnwHZDDPu3568Tmdm4D59FtNsOedZHNrtroCKnOZnRZfsWhQYDzK7/7QnlqWBbPRdw9AgdipND3RK85gySsne7SUlDRrF2DRvKefxgeXPysR8URRHDbcCPxFDkdKbpXOEbn2ur8hC1ipKwqxEWkK5fQEmayYkNQOFmnjyRukGoH5JT48QOMJUsDWLfrDq6kpyAI3nk4RNw32tgavOQ28UCefj8gf/JXbsqVq8hW/L4LQLN7eai97hqz3Ew4MsqleDDroY88axTkMJG/dBg55YASs7ZwJYaIMBrryAAmXj+uB4TzDN/uKdZpkPek6WzuLKmcOb7K1WCYuqTPXbEdsJSkKtxz9xFGF9P1/jKFcQK0t+RalvL+i11hGsrkDfNu4xehmdKHzKiyUcH7wxOWc3iG4kbmmYUMY0Ynf+zSCE/GJ2ABRp24k1dfwJnd1WflqhGyIcd3jrzGX7zEI4TWPA/37XYx9S6fG7MdX2vbJliRGxzWWUKXECcSRqZH8bx3gdUeM00zbBS9v7xfYVcu9c3VxhxOz3U5XKzbozeffysOhpRuxMAze6M+fH6pF/Yq335qB699Qm4JctP30itXTH463fpc4L1/kQ+YoRJ16VFjSs=


before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      sudo apt-get -y install python3 python3-setuptools

      echo "No need to install PyQt5. It is required during execution only"

      # Builds, directory for temporay installation
      mkdir -p builds
      chmod a+rw builds

      ## Install sip and pyqt5
      #export DISPLAY=:99.0
      #sh -e /etc/init.d/xvfb start

      # Cached Downloads
      #sudo mkdir -p /downloads
      #sudo chmod a+rw /downloads
      #curl -L -o /downloads/sip.tar.gz https://nchc.dl.sourceforge.net/project/pyqt/sip/sip-4.18/sip-4.18.tar.gz
      #curl -L -o /downloads/PyQt5_gpl-5.6.tar.gz https://superb-dca2.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz

      # Qt5
      #sudo add-apt-repository -y ppa:beineri/opt-qt562
      #sudo apt-get update
      #sudo apt-get install -y qt56base

      # Builds
      #pushd /builds

      # SIP
      #tar xzf /downloads/sip.tar.gz --keep-newer-files
      #pushd sip-4.18
      #python configure.py
      #make
      #sudo make install
      #popd

      # PyQt5
      #source /opt/qt56/bin/qt56-env.sh  # switch to Qt5
      #tar xzf /downloads/PyQt5_gpl-5.6.tar.gz --keep-newer-files
      #pushd PyQt5_gpl-5.6
      #python configure.py -c --confirm-license --verbose --no-designer-plugin -e QtWidgets -e QtCore -e QtGui -e QtPrintSupport
      #make
      #sudo make install
      #popd

      # Out from builds
      #popd

      # Install patchelf
      pushd builds
      git clone https://github.com/NixOS/patchelf
      #curl -L -o patchelf-0.9.tar.gz https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
      #tar -zxvf patchelf-0.9.tar.gz
      pushd patchelf
      ./bootstrap.sh
      ./configure && make && sudo make install
      popd
      popd

    else
      brew update
      brew cask uninstall oclint
      brew install gcc@5 --without-multilib
      brew outdated pyenv || brew upgrade pyenv
      eval "$(pyenv init -)"

      case "${TOXENV}" in
        py34)
          PYVER=3.4
          # Install the latest release of the specified Python version using pyenv.
          PYVER="$(pyenv install --list | grep -E "^\\s*$PYVER" | sort -n -t. -k3 | tail -n1)"
          pyenv install $PYVER
          pyenv global $PYVER
          echo "Selected Python $PYVER"
          python --version
          ;;
        py35)
          PYVER=3.5
          # Install the latest release of the specified Python version using pyenv.
          PYVER="$(pyenv install --list | grep -E "^\\s*$PYVER" | sort -n -t. -k3 | tail -n1)"
          pyenv install $PYVER
          pyenv global $PYVER
          echo "Selected Python $PYVER"
          python --version
          ;;
        py36)
          PYVER=3.6
          # Install the latest release of the specified Python version using pyenv.
          PYVER="$(pyenv install --list | grep -E "^\\s*$PYVER" | sort -n -t. -k3 | tail -n1)"
          pyenv install $PYVER
          pyenv global $PYVER
          echo "Selected Python $PYVER"
          python --version
          ;;
      esac

      export CC=gcc-5
      export CXX=g++-5

      # brew install pyqt5 --with-python3
    fi

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      export CC=gcc-5
      export CXX=g++-5
    fi
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install Cython --install-option="--no-cython-compile"
    pip install uninstall numpy
    pip install install numpy
    pip install --upgrade scipy
    pip install --upgrade matplotlib
    pip install --upgrade h5py
    pip install --upgrade sklearn

    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      pip install auditwheel
    else
      pip install --upgrade coverage coveralls flake8 pep8
      export CC=gcc
      export CXX=g++
      pip install psutil
      export CC=gcc-5
      export CXX=g++-5
    fi

    # Install gcMapExplorer
    pip install -ve .

script:
  - python -c 'import gcMapExplorer'
  - python -c 'import gcMapExplorer.lib as gmlib'

after_success:
  # Specify account details for PyPI
  - |
    echo "[distutils]"                                  > ~/.pypirc
    echo "index-servers ="                             >> ~/.pypirc
    echo "    pypi"                                    >> ~/.pypirc
    echo "[pypi]"                                      >> ~/.pypirc
    echo "    username: rjdkmr"                         >> ~/.pypirc
    echo "    password: $PYPIPASSWORD"                  >> ~/.pypirc

  # For OS X and tags only, build a Python source distribution and "binary
  # wheel" and upload these to PyPI. Note that the source upload will only
  # succeed the first time and will be skipped by twine in subsiquent attempts.
  - |
    pip install --upgrade twine
    export TWINE_USERNAME=rjdkmr
    export TWINE_PASSWORD=$PYPIPASSWORD
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      pip wheel --no-deps --no-cache-dir -w wheels .
      auditwheel show wheels/*.whl
      auditwheel repair wheels/*.whl
      twine upload -u rjdkmr -p $PYPIPASSWORD --skip-existing wheelhouse/*
      python setup.py sdist
    else
      python setup.py sdist bdist_wheel
    fi
    twine upload -u rjdkmr -p $PYPIPASSWORD --skip-existing dist/*
